BEGIN

  DBMS_OUTPUT.PUT_LINE('Simple IF THEN END IF');
  IF TRUE THEN
    DBMS_OUTPUT.PUT_LINE('TRUE');
  END IF;

  DBMS_OUTPUT.PUT_LINE('IF THEN ELSE END IF');
  IF FALSE THEN
    DBMS_OUTPUT.PUT_LINE('TRUE');
  ELSE
    DBMS_OUTPUT.PUT_LINE('FALSE');
  END IF;

  DBMS_OUTPUT.PUT_LINE('IF THEN ELSIF ELSE END IF');
  IF 3 < 3 THEN
    DBMS_OUTPUT.PUT_LINE('NOPE ... THATS NOT TRUE');
  ELSIF (3 = 3) THEN
    DBMS_OUTPUT.PUT_LINE('NOW ... THATS TRUE');
  ELSE
    DBMS_OUTPUT.PUT_LINE('THIS DEFINATELY NEVER GONNA HAPPEN');
  END IF;

  DECLARE
    v_val NUMBER := 130;
    BEGIN
    CASE
      WHEN v_val = 8 THEN DBMS_OUTPUT.PUT_LINE('ITS 8');
      WHEN v_val = 9 THEN DBMS_OUTPUT.PUT_LINE('ITS 9');
      WHEN v_val = 10 THEN DBMS_OUTPUT.PUT_LINE('ITS 10');
      WHEN v_val = 11 THEN DBMS_OUTPUT.PUT_LINE('ITS 11');
      WHEN v_val = 12 THEN DBMS_OUTPUT.PUT_LINE('ITS 12');
      ELSE DBMS_OUTPUT.PUT_LINE('WHAT IS IT THEN?');
    END CASE;
  END;

  BEGIN
    IF TRUE THEN
      GOTO awesome_statement;
      DBMS_OUTPUT.PUT_LINE('THIS IS AWESOME');
      <<awesome_statement>>
      DBMS_OUTPUT.PUT_LINE('THIS IS NICE.');
    END IF;
  END;

END;
